CREATE TABLE [dbo].[CompanyInfo] (
    [companyID]                INT            IDENTITY (1, 1) NOT NULL,
    [companyName]              NVARCHAR (500) NULL,
    [companyAddress]           NVARCHAR (500) NULL,
    [companyTelePhone]         NVARCHAR (500) NULL,
    [companyLogo]              NVARCHAR (500) NULL,
    [contactPerson]            NVARCHAR (500) NULL,
    [contactPhone]             NVARCHAR (500) NULL,
    [companyStatus]            INT            NULL,
    [companyImagePath]         NVARCHAR (500) NULL,
    [companyDescription]       NVARCHAR (500) NULL,
    [defaultMenuId]            INT            NULL,
    [freeRefundHour]           FLOAT (53)     NULL,
    [viewallocCommissionType]  TINYINT        NULL,
    [viewallocCommissionValue] FLOAT (53)     NULL,
    [prepayOrderCount]         BIGINT         NULL,
    [prePayCashBackCount]      TINYINT        NULL,
    [prePayVIPCount]           TINYINT        NULL,
    [prePaySendGiftCount]      TINYINT        NULL,
    [recommendRating]          TINYINT        NULL,
    [preorderCount]            BIGINT         NULL,
    [sinaWeiboName]            NVARCHAR (100) NULL,
    [acpp]                     FLOAT (53)     NULL,
    [applyLimitHours]          INT            NULL,
    [qqWeiboName]              NVARCHAR (100) NULL,
    [wechatPublicName]         NVARCHAR (100) NULL,
    [ownedCompany]             NVARCHAR (500) NULL,
    CONSTRAINT [PK_CompanyInfo] PRIMARY KEY CLUSTERED ([companyID] ASC)
);

