//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.JianzhouService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.nineorange.com", ConfigurationName="JianzhouService.BusinessService")]
    public interface BusinessService {
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        SMS.JianzhouService.getReceivedMsgResponse getReceivedMsg(SMS.JianzhouService.getReceivedMsg request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        SMS.JianzhouService.sendBatchMessageTimelyExtResponse sendBatchMessageTimelyExt(SMS.JianzhouService.sendBatchMessageTimelyExt request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        SMS.JianzhouService.sendPersonalMessagesResponse sendPersonalMessages(SMS.JianzhouService.sendPersonalMessages request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        SMS.JianzhouService.modifyPasswordResponse modifyPassword(SMS.JianzhouService.modifyPassword request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        SMS.JianzhouService.getReceiptResponse getReceipt(SMS.JianzhouService.getReceipt request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        SMS.JianzhouService.sendBatchMessageResponse sendBatchMessage(SMS.JianzhouService.sendBatchMessage request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        SMS.JianzhouService.sendGjBatchMessageResponse sendGjBatchMessage(SMS.JianzhouService.sendGjBatchMessage request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        SMS.JianzhouService.validateUserResponse validateUser(SMS.JianzhouService.validateUser request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        SMS.JianzhouService.sendMessageResponse sendMessage(SMS.JianzhouService.sendMessage request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        SMS.JianzhouService.sendTimelyMessageResponse sendTimelyMessage(SMS.JianzhouService.sendTimelyMessage request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        SMS.JianzhouService.sendMmsMessagesResponse sendMmsMessages(SMS.JianzhouService.sendMmsMessages request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        SMS.JianzhouService.gxmtResponse gxmt(SMS.JianzhouService.gxmt request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        SMS.JianzhouService.getUserInfoResponse getUserInfo(SMS.JianzhouService.getUserInfo request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        SMS.JianzhouService.sendAudioResponse sendAudio(SMS.JianzhouService.sendAudio request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReceivedMsg {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getReceivedMsg", Namespace="http://service.nineorange.com", Order=0)]
        public SMS.JianzhouService.getReceivedMsgBody Body;
        
        public getReceivedMsg() {
        }
        
        public getReceivedMsg(SMS.JianzhouService.getReceivedMsgBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class getReceivedMsgBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int param;
        
        public getReceivedMsgBody() {
        }
        
        public getReceivedMsgBody(string account, string password, int param) {
            this.account = account;
            this.password = password;
            this.param = param;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReceivedMsgResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getReceivedMsgResponse", Namespace="http://service.nineorange.com", Order=0)]
        public SMS.JianzhouService.getReceivedMsgResponseBody Body;
        
        public getReceivedMsgResponse() {
        }
        
        public getReceivedMsgResponse(SMS.JianzhouService.getReceivedMsgResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class getReceivedMsgResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getReceivedMsgReturn;
        
        public getReceivedMsgResponseBody() {
        }
        
        public getReceivedMsgResponseBody(string getReceivedMsgReturn) {
            this.getReceivedMsgReturn = getReceivedMsgReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendBatchMessageTimelyExt {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendBatchMessageTimelyExt", Namespace="http://service.nineorange.com", Order=0)]
        public SMS.JianzhouService.sendBatchMessageTimelyExtBody Body;
        
        public sendBatchMessageTimelyExt() {
        }
        
        public sendBatchMessageTimelyExt(SMS.JianzhouService.sendBatchMessageTimelyExtBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendBatchMessageTimelyExtBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sendDateTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string destmobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string msgText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ext;
        
        public sendBatchMessageTimelyExtBody() {
        }
        
        public sendBatchMessageTimelyExtBody(string account, string password, string sendDateTime, string destmobile, string msgText, string ext) {
            this.account = account;
            this.password = password;
            this.sendDateTime = sendDateTime;
            this.destmobile = destmobile;
            this.msgText = msgText;
            this.ext = ext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendBatchMessageTimelyExtResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendBatchMessageTimelyExtResponse", Namespace="http://service.nineorange.com", Order=0)]
        public SMS.JianzhouService.sendBatchMessageTimelyExtResponseBody Body;
        
        public sendBatchMessageTimelyExtResponse() {
        }
        
        public sendBatchMessageTimelyExtResponse(SMS.JianzhouService.sendBatchMessageTimelyExtResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendBatchMessageTimelyExtResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        public sendBatchMessageTimelyExtResponseBody() {
        }
        
        public sendBatchMessageTimelyExtResponseBody(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendPersonalMessages {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendPersonalMessages", Namespace="http://service.nineorange.com", Order=0)]
        public SMS.JianzhouService.sendPersonalMessagesBody Body;
        
        public sendPersonalMessages() {
        }
        
        public sendPersonalMessages(SMS.JianzhouService.sendPersonalMessagesBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendPersonalMessagesBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string destMobiles;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string msgContents;
        
        public sendPersonalMessagesBody() {
        }
        
        public sendPersonalMessagesBody(string account, string password, string destMobiles, string msgContents) {
            this.account = account;
            this.password = password;
            this.destMobiles = destMobiles;
            this.msgContents = msgContents;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendPersonalMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendPersonalMessagesResponse", Namespace="http://service.nineorange.com", Order=0)]
        public SMS.JianzhouService.sendPersonalMessagesResponseBody Body;
        
        public sendPersonalMessagesResponse() {
        }
        
        public sendPersonalMessagesResponse(SMS.JianzhouService.sendPersonalMessagesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendPersonalMessagesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sendPersonalMessagesReturn;
        
        public sendPersonalMessagesResponseBody() {
        }
        
        public sendPersonalMessagesResponseBody(int sendPersonalMessagesReturn) {
            this.sendPersonalMessagesReturn = sendPersonalMessagesReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class modifyPassword {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="modifyPassword", Namespace="http://service.nineorange.com", Order=0)]
        public SMS.JianzhouService.modifyPasswordBody Body;
        
        public modifyPassword() {
        }
        
        public modifyPassword(SMS.JianzhouService.modifyPasswordBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class modifyPasswordBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string oldPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string newPassword;
        
        public modifyPasswordBody() {
        }
        
        public modifyPasswordBody(string account, string oldPassword, string newPassword) {
            this.account = account;
            this.oldPassword = oldPassword;
            this.newPassword = newPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class modifyPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="modifyPasswordResponse", Namespace="http://service.nineorange.com", Order=0)]
        public SMS.JianzhouService.modifyPasswordResponseBody Body;
        
        public modifyPasswordResponse() {
        }
        
        public modifyPasswordResponse(SMS.JianzhouService.modifyPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class modifyPasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int modifyPasswordReturn;
        
        public modifyPasswordResponseBody() {
        }
        
        public modifyPasswordResponseBody(int modifyPasswordReturn) {
            this.modifyPasswordReturn = modifyPasswordReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReceipt {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getReceipt", Namespace="http://service.nineorange.com", Order=0)]
        public SMS.JianzhouService.getReceiptBody Body;
        
        public getReceipt() {
        }
        
        public getReceipt(SMS.JianzhouService.getReceiptBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class getReceiptBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int taskID;
        
        public getReceiptBody() {
        }
        
        public getReceiptBody(string account, string password, int taskID) {
            this.account = account;
            this.password = password;
            this.taskID = taskID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReceiptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getReceiptResponse", Namespace="http://service.nineorange.com", Order=0)]
        public SMS.JianzhouService.getReceiptResponseBody Body;
        
        public getReceiptResponse() {
        }
        
        public getReceiptResponse(SMS.JianzhouService.getReceiptResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class getReceiptResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getReceiptReturn;
        
        public getReceiptResponseBody() {
        }
        
        public getReceiptResponseBody(string getReceiptReturn) {
            this.getReceiptReturn = getReceiptReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendBatchMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendBatchMessage", Namespace="http://service.nineorange.com", Order=0)]
        public SMS.JianzhouService.sendBatchMessageBody Body;
        
        public sendBatchMessage() {
        }
        
        public sendBatchMessage(SMS.JianzhouService.sendBatchMessageBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendBatchMessageBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string destmobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string msgText;
        
        public sendBatchMessageBody() {
        }
        
        public sendBatchMessageBody(string account, string password, string destmobile, string msgText) {
            this.account = account;
            this.password = password;
            this.destmobile = destmobile;
            this.msgText = msgText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendBatchMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendBatchMessageResponse", Namespace="http://service.nineorange.com", Order=0)]
        public SMS.JianzhouService.sendBatchMessageResponseBody Body;
        
        public sendBatchMessageResponse() {
        }
        
        public sendBatchMessageResponse(SMS.JianzhouService.sendBatchMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendBatchMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sendBatchMessageReturn;
        
        public sendBatchMessageResponseBody() {
        }
        
        public sendBatchMessageResponseBody(int sendBatchMessageReturn) {
            this.sendBatchMessageReturn = sendBatchMessageReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendGjBatchMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendGjBatchMessage", Namespace="http://service.nineorange.com", Order=0)]
        public SMS.JianzhouService.sendGjBatchMessageBody Body;
        
        public sendGjBatchMessage() {
        }
        
        public sendGjBatchMessage(SMS.JianzhouService.sendGjBatchMessageBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendGjBatchMessageBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sendDateTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string destmobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string msgText;
        
        public sendGjBatchMessageBody() {
        }
        
        public sendGjBatchMessageBody(string account, string password, string sendDateTime, string destmobile, string msgText) {
            this.account = account;
            this.password = password;
            this.sendDateTime = sendDateTime;
            this.destmobile = destmobile;
            this.msgText = msgText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendGjBatchMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendGjBatchMessageResponse", Namespace="http://service.nineorange.com", Order=0)]
        public SMS.JianzhouService.sendGjBatchMessageResponseBody Body;
        
        public sendGjBatchMessageResponse() {
        }
        
        public sendGjBatchMessageResponse(SMS.JianzhouService.sendGjBatchMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendGjBatchMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        public sendGjBatchMessageResponseBody() {
        }
        
        public sendGjBatchMessageResponseBody(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validateUser {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validateUser", Namespace="http://service.nineorange.com", Order=0)]
        public SMS.JianzhouService.validateUserBody Body;
        
        public validateUser() {
        }
        
        public validateUser(SMS.JianzhouService.validateUserBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class validateUserBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public validateUserBody() {
        }
        
        public validateUserBody(string account, string password) {
            this.account = account;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validateUserResponse", Namespace="http://service.nineorange.com", Order=0)]
        public SMS.JianzhouService.validateUserResponseBody Body;
        
        public validateUserResponse() {
        }
        
        public validateUserResponse(SMS.JianzhouService.validateUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class validateUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int validateUserReturn;
        
        public validateUserResponseBody() {
        }
        
        public validateUserResponseBody(int validateUserReturn) {
            this.validateUserReturn = validateUserReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendMessage", Namespace="http://service.nineorange.com", Order=0)]
        public SMS.JianzhouService.sendMessageBody Body;
        
        public sendMessage() {
        }
        
        public sendMessage(SMS.JianzhouService.sendMessageBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendMessageBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string destmobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string msgText;
        
        public sendMessageBody() {
        }
        
        public sendMessageBody(string account, string password, string destmobile, string msgText) {
            this.account = account;
            this.password = password;
            this.destmobile = destmobile;
            this.msgText = msgText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendMessageResponse", Namespace="http://service.nineorange.com", Order=0)]
        public SMS.JianzhouService.sendMessageResponseBody Body;
        
        public sendMessageResponse() {
        }
        
        public sendMessageResponse(SMS.JianzhouService.sendMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sendMessageReturn;
        
        public sendMessageResponseBody() {
        }
        
        public sendMessageResponseBody(int sendMessageReturn) {
            this.sendMessageReturn = sendMessageReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendTimelyMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendTimelyMessage", Namespace="http://service.nineorange.com", Order=0)]
        public SMS.JianzhouService.sendTimelyMessageBody Body;
        
        public sendTimelyMessage() {
        }
        
        public sendTimelyMessage(SMS.JianzhouService.sendTimelyMessageBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendTimelyMessageBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sendDateTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string destmobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string msgText;
        
        public sendTimelyMessageBody() {
        }
        
        public sendTimelyMessageBody(string account, string password, string sendDateTime, string destmobile, string msgText) {
            this.account = account;
            this.password = password;
            this.sendDateTime = sendDateTime;
            this.destmobile = destmobile;
            this.msgText = msgText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendTimelyMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendTimelyMessageResponse", Namespace="http://service.nineorange.com", Order=0)]
        public SMS.JianzhouService.sendTimelyMessageResponseBody Body;
        
        public sendTimelyMessageResponse() {
        }
        
        public sendTimelyMessageResponse(SMS.JianzhouService.sendTimelyMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendTimelyMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sendTimelyMessageReturn;
        
        public sendTimelyMessageResponseBody() {
        }
        
        public sendTimelyMessageResponseBody(int sendTimelyMessageReturn) {
            this.sendTimelyMessageReturn = sendTimelyMessageReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMmsMessages {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendMmsMessages", Namespace="http://service.nineorange.com", Order=0)]
        public SMS.JianzhouService.sendMmsMessagesBody Body;
        
        public sendMmsMessages() {
        }
        
        public sendMmsMessages(SMS.JianzhouService.sendMmsMessagesBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendMmsMessagesBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string phones;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string mmsString;
        
        public sendMmsMessagesBody() {
        }
        
        public sendMmsMessagesBody(string account, string password, string phones, string mmsString) {
            this.account = account;
            this.password = password;
            this.phones = phones;
            this.mmsString = mmsString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMmsMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendMmsMessagesResponse", Namespace="http://service.nineorange.com", Order=0)]
        public SMS.JianzhouService.sendMmsMessagesResponseBody Body;
        
        public sendMmsMessagesResponse() {
        }
        
        public sendMmsMessagesResponse(SMS.JianzhouService.sendMmsMessagesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendMmsMessagesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sendMmsMessagesReturn;
        
        public sendMmsMessagesResponseBody() {
        }
        
        public sendMmsMessagesResponseBody(int sendMmsMessagesReturn) {
            this.sendMmsMessagesReturn = sendMmsMessagesReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class gxmt {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="gxmt", Namespace="http://service.nineorange.com", Order=0)]
        public SMS.JianzhouService.gxmtBody Body;
        
        public gxmt() {
        }
        
        public gxmt(SMS.JianzhouService.gxmtBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class gxmtBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sendDateTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string destmobiles;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string msgTexts;
        
        public gxmtBody() {
        }
        
        public gxmtBody(string account, string password, string sendDateTime, string destmobiles, string msgTexts) {
            this.account = account;
            this.password = password;
            this.sendDateTime = sendDateTime;
            this.destmobiles = destmobiles;
            this.msgTexts = msgTexts;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class gxmtResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="gxmtResponse", Namespace="http://service.nineorange.com", Order=0)]
        public SMS.JianzhouService.gxmtResponseBody Body;
        
        public gxmtResponse() {
        }
        
        public gxmtResponse(SMS.JianzhouService.gxmtResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class gxmtResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int gxmtReturn;
        
        public gxmtResponseBody() {
        }
        
        public gxmtResponseBody(int gxmtReturn) {
            this.gxmtReturn = gxmtReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserInfo", Namespace="http://service.nineorange.com", Order=0)]
        public SMS.JianzhouService.getUserInfoBody Body;
        
        public getUserInfo() {
        }
        
        public getUserInfo(SMS.JianzhouService.getUserInfoBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class getUserInfoBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public getUserInfoBody() {
        }
        
        public getUserInfoBody(string account, string password) {
            this.account = account;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserInfoResponse", Namespace="http://service.nineorange.com", Order=0)]
        public SMS.JianzhouService.getUserInfoResponseBody Body;
        
        public getUserInfoResponse() {
        }
        
        public getUserInfoResponse(SMS.JianzhouService.getUserInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class getUserInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getUserInfoReturn;
        
        public getUserInfoResponseBody() {
        }
        
        public getUserInfoResponseBody(string getUserInfoReturn) {
            this.getUserInfoReturn = getUserInfoReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendAudio {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendAudio", Namespace="http://service.nineorange.com", Order=0)]
        public SMS.JianzhouService.sendAudioBody Body;
        
        public sendAudio() {
        }
        
        public sendAudio(SMS.JianzhouService.sendAudioBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendAudioBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sendDateTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string destmobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string msgText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string srcMobile;
        
        public sendAudioBody() {
        }
        
        public sendAudioBody(string account, string password, string sendDateTime, string destmobile, string msgText, string srcMobile) {
            this.account = account;
            this.password = password;
            this.sendDateTime = sendDateTime;
            this.destmobile = destmobile;
            this.msgText = msgText;
            this.srcMobile = srcMobile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendAudioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendAudioResponse", Namespace="http://service.nineorange.com", Order=0)]
        public SMS.JianzhouService.sendAudioResponseBody Body;
        
        public sendAudioResponse() {
        }
        
        public sendAudioResponse(SMS.JianzhouService.sendAudioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendAudioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        public sendAudioResponseBody() {
        }
        
        public sendAudioResponseBody(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BusinessServiceChannel : SMS.JianzhouService.BusinessService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BusinessServiceClient : System.ServiceModel.ClientBase<SMS.JianzhouService.BusinessService>, SMS.JianzhouService.BusinessService {
        
        public BusinessServiceClient() {
        }
        
        public BusinessServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BusinessServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusinessServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusinessServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SMS.JianzhouService.getReceivedMsgResponse SMS.JianzhouService.BusinessService.getReceivedMsg(SMS.JianzhouService.getReceivedMsg request) {
            return base.Channel.getReceivedMsg(request);
        }
        
        public string getReceivedMsg(string account, string password, int param) {
            SMS.JianzhouService.getReceivedMsg inValue = new SMS.JianzhouService.getReceivedMsg();
            inValue.Body = new SMS.JianzhouService.getReceivedMsgBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.param = param;
            SMS.JianzhouService.getReceivedMsgResponse retVal = ((SMS.JianzhouService.BusinessService)(this)).getReceivedMsg(inValue);
            return retVal.Body.getReceivedMsgReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SMS.JianzhouService.sendBatchMessageTimelyExtResponse SMS.JianzhouService.BusinessService.sendBatchMessageTimelyExt(SMS.JianzhouService.sendBatchMessageTimelyExt request) {
            return base.Channel.sendBatchMessageTimelyExt(request);
        }
        
        public int sendBatchMessageTimelyExt(string account, string password, string sendDateTime, string destmobile, string msgText, string ext) {
            SMS.JianzhouService.sendBatchMessageTimelyExt inValue = new SMS.JianzhouService.sendBatchMessageTimelyExt();
            inValue.Body = new SMS.JianzhouService.sendBatchMessageTimelyExtBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.sendDateTime = sendDateTime;
            inValue.Body.destmobile = destmobile;
            inValue.Body.msgText = msgText;
            inValue.Body.ext = ext;
            SMS.JianzhouService.sendBatchMessageTimelyExtResponse retVal = ((SMS.JianzhouService.BusinessService)(this)).sendBatchMessageTimelyExt(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SMS.JianzhouService.sendPersonalMessagesResponse SMS.JianzhouService.BusinessService.sendPersonalMessages(SMS.JianzhouService.sendPersonalMessages request) {
            return base.Channel.sendPersonalMessages(request);
        }
        
        public int sendPersonalMessages(string account, string password, string destMobiles, string msgContents) {
            SMS.JianzhouService.sendPersonalMessages inValue = new SMS.JianzhouService.sendPersonalMessages();
            inValue.Body = new SMS.JianzhouService.sendPersonalMessagesBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.destMobiles = destMobiles;
            inValue.Body.msgContents = msgContents;
            SMS.JianzhouService.sendPersonalMessagesResponse retVal = ((SMS.JianzhouService.BusinessService)(this)).sendPersonalMessages(inValue);
            return retVal.Body.sendPersonalMessagesReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SMS.JianzhouService.modifyPasswordResponse SMS.JianzhouService.BusinessService.modifyPassword(SMS.JianzhouService.modifyPassword request) {
            return base.Channel.modifyPassword(request);
        }
        
        public int modifyPassword(string account, string oldPassword, string newPassword) {
            SMS.JianzhouService.modifyPassword inValue = new SMS.JianzhouService.modifyPassword();
            inValue.Body = new SMS.JianzhouService.modifyPasswordBody();
            inValue.Body.account = account;
            inValue.Body.oldPassword = oldPassword;
            inValue.Body.newPassword = newPassword;
            SMS.JianzhouService.modifyPasswordResponse retVal = ((SMS.JianzhouService.BusinessService)(this)).modifyPassword(inValue);
            return retVal.Body.modifyPasswordReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SMS.JianzhouService.getReceiptResponse SMS.JianzhouService.BusinessService.getReceipt(SMS.JianzhouService.getReceipt request) {
            return base.Channel.getReceipt(request);
        }
        
        public string getReceipt(string account, string password, int taskID) {
            SMS.JianzhouService.getReceipt inValue = new SMS.JianzhouService.getReceipt();
            inValue.Body = new SMS.JianzhouService.getReceiptBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.taskID = taskID;
            SMS.JianzhouService.getReceiptResponse retVal = ((SMS.JianzhouService.BusinessService)(this)).getReceipt(inValue);
            return retVal.Body.getReceiptReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SMS.JianzhouService.sendBatchMessageResponse SMS.JianzhouService.BusinessService.sendBatchMessage(SMS.JianzhouService.sendBatchMessage request) {
            return base.Channel.sendBatchMessage(request);
        }
        
        public int sendBatchMessage(string account, string password, string destmobile, string msgText) {
            SMS.JianzhouService.sendBatchMessage inValue = new SMS.JianzhouService.sendBatchMessage();
            inValue.Body = new SMS.JianzhouService.sendBatchMessageBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.destmobile = destmobile;
            inValue.Body.msgText = msgText;
            SMS.JianzhouService.sendBatchMessageResponse retVal = ((SMS.JianzhouService.BusinessService)(this)).sendBatchMessage(inValue);
            return retVal.Body.sendBatchMessageReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SMS.JianzhouService.sendGjBatchMessageResponse SMS.JianzhouService.BusinessService.sendGjBatchMessage(SMS.JianzhouService.sendGjBatchMessage request) {
            return base.Channel.sendGjBatchMessage(request);
        }
        
        public int sendGjBatchMessage(string account, string password, string sendDateTime, string destmobile, string msgText) {
            SMS.JianzhouService.sendGjBatchMessage inValue = new SMS.JianzhouService.sendGjBatchMessage();
            inValue.Body = new SMS.JianzhouService.sendGjBatchMessageBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.sendDateTime = sendDateTime;
            inValue.Body.destmobile = destmobile;
            inValue.Body.msgText = msgText;
            SMS.JianzhouService.sendGjBatchMessageResponse retVal = ((SMS.JianzhouService.BusinessService)(this)).sendGjBatchMessage(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SMS.JianzhouService.validateUserResponse SMS.JianzhouService.BusinessService.validateUser(SMS.JianzhouService.validateUser request) {
            return base.Channel.validateUser(request);
        }
        
        public int validateUser(string account, string password) {
            SMS.JianzhouService.validateUser inValue = new SMS.JianzhouService.validateUser();
            inValue.Body = new SMS.JianzhouService.validateUserBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            SMS.JianzhouService.validateUserResponse retVal = ((SMS.JianzhouService.BusinessService)(this)).validateUser(inValue);
            return retVal.Body.validateUserReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SMS.JianzhouService.sendMessageResponse SMS.JianzhouService.BusinessService.sendMessage(SMS.JianzhouService.sendMessage request) {
            return base.Channel.sendMessage(request);
        }
        
        public int sendMessage(string account, string password, string destmobile, string msgText) {
            SMS.JianzhouService.sendMessage inValue = new SMS.JianzhouService.sendMessage();
            inValue.Body = new SMS.JianzhouService.sendMessageBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.destmobile = destmobile;
            inValue.Body.msgText = msgText;
            SMS.JianzhouService.sendMessageResponse retVal = ((SMS.JianzhouService.BusinessService)(this)).sendMessage(inValue);
            return retVal.Body.sendMessageReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SMS.JianzhouService.sendTimelyMessageResponse SMS.JianzhouService.BusinessService.sendTimelyMessage(SMS.JianzhouService.sendTimelyMessage request) {
            return base.Channel.sendTimelyMessage(request);
        }
        
        public int sendTimelyMessage(string account, string password, string sendDateTime, string destmobile, string msgText) {
            SMS.JianzhouService.sendTimelyMessage inValue = new SMS.JianzhouService.sendTimelyMessage();
            inValue.Body = new SMS.JianzhouService.sendTimelyMessageBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.sendDateTime = sendDateTime;
            inValue.Body.destmobile = destmobile;
            inValue.Body.msgText = msgText;
            SMS.JianzhouService.sendTimelyMessageResponse retVal = ((SMS.JianzhouService.BusinessService)(this)).sendTimelyMessage(inValue);
            return retVal.Body.sendTimelyMessageReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SMS.JianzhouService.sendMmsMessagesResponse SMS.JianzhouService.BusinessService.sendMmsMessages(SMS.JianzhouService.sendMmsMessages request) {
            return base.Channel.sendMmsMessages(request);
        }
        
        public int sendMmsMessages(string account, string password, string phones, string mmsString) {
            SMS.JianzhouService.sendMmsMessages inValue = new SMS.JianzhouService.sendMmsMessages();
            inValue.Body = new SMS.JianzhouService.sendMmsMessagesBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.phones = phones;
            inValue.Body.mmsString = mmsString;
            SMS.JianzhouService.sendMmsMessagesResponse retVal = ((SMS.JianzhouService.BusinessService)(this)).sendMmsMessages(inValue);
            return retVal.Body.sendMmsMessagesReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SMS.JianzhouService.gxmtResponse SMS.JianzhouService.BusinessService.gxmt(SMS.JianzhouService.gxmt request) {
            return base.Channel.gxmt(request);
        }
        
        public int gxmt(string account, string password, string sendDateTime, string destmobiles, string msgTexts) {
            SMS.JianzhouService.gxmt inValue = new SMS.JianzhouService.gxmt();
            inValue.Body = new SMS.JianzhouService.gxmtBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.sendDateTime = sendDateTime;
            inValue.Body.destmobiles = destmobiles;
            inValue.Body.msgTexts = msgTexts;
            SMS.JianzhouService.gxmtResponse retVal = ((SMS.JianzhouService.BusinessService)(this)).gxmt(inValue);
            return retVal.Body.gxmtReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SMS.JianzhouService.getUserInfoResponse SMS.JianzhouService.BusinessService.getUserInfo(SMS.JianzhouService.getUserInfo request) {
            return base.Channel.getUserInfo(request);
        }
        
        public string getUserInfo(string account, string password) {
            SMS.JianzhouService.getUserInfo inValue = new SMS.JianzhouService.getUserInfo();
            inValue.Body = new SMS.JianzhouService.getUserInfoBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            SMS.JianzhouService.getUserInfoResponse retVal = ((SMS.JianzhouService.BusinessService)(this)).getUserInfo(inValue);
            return retVal.Body.getUserInfoReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SMS.JianzhouService.sendAudioResponse SMS.JianzhouService.BusinessService.sendAudio(SMS.JianzhouService.sendAudio request) {
            return base.Channel.sendAudio(request);
        }
        
        public int sendAudio(string account, string password, string sendDateTime, string destmobile, string msgText, string srcMobile) {
            SMS.JianzhouService.sendAudio inValue = new SMS.JianzhouService.sendAudio();
            inValue.Body = new SMS.JianzhouService.sendAudioBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.sendDateTime = sendDateTime;
            inValue.Body.destmobile = destmobile;
            inValue.Body.msgText = msgText;
            inValue.Body.srcMobile = srcMobile;
            SMS.JianzhouService.sendAudioResponse retVal = ((SMS.JianzhouService.BusinessService)(this)).sendAudio(inValue);
            return retVal.Body.@return;
        }
    }
}
