CREATE TABLE [dbo].[CouponInfo] (
    [couponID]               BIGINT         IDENTITY (1, 1) NOT NULL,
    [couponName]             NVARCHAR (500) NULL,
    [couponDesc]             NVARCHAR (500) NULL,
    [couponDisplayStartTime] DATETIME       NULL,
    [couponDisplayEndTime]   DATETIME       NULL,
    [couponValidStartTime]   DATETIME       NULL,
    [couponValidEndTime]     DATETIME       NULL,
    [couponCreatTime]        DATETIME       NULL,
    [couponRefreshTime]      DATETIME       NULL,
    [couponStatus]           INT            NULL,
    [couponType]             INT            NULL,
    [originaQuantity]        INT            NULL,
    [currentQuantity]        INT            NULL,
    [originalPrice]          FLOAT (53)     NULL,
    [currentPrice]           FLOAT (53)     NULL,
    [companyId]              INT            NULL,
    [couponRequirementType]  INT            NULL,
    [isVIPOnly]              BIT            NULL,
    [couponDownloadPrice]    FLOAT (53)     NULL,
    [discount]               FLOAT (53)     NULL,
    [discountedAmount]       FLOAT (53)     NULL,
    [downloadQuantity]       INT            NULL,
    [canDownloadOnlyOnce]    BIT            NULL,
    [couponVerifyReward]     FLOAT (53)     NULL,
    [viewedCount]            INT            NULL,
    [verifyCount]            INT            NULL,
    [prePayCashBackCount]    TINYINT        NULL,
    [prePayVIPCount]         TINYINT        NULL,
    [prePaySendGiftCount]    TINYINT        NULL,
    [canUseNumberOnesOrder]  INT            NULL,
    [lowPayment]             FLOAT (53)     NULL,
    [prompt]                 VARCHAR (500)  NULL,
    CONSTRAINT [PK_CouponInfo] PRIMARY KEY CLUSTERED ([couponID] ASC)
);

