CREATE TABLE [dbo].[ShopInfo] (
    [shopID]                      INT            IDENTITY (1, 1) NOT NULL,
    [companyID]                   INT            NULL,
    [shopName]                    NVARCHAR (500) NULL,
    [shopAddress]                 NVARCHAR (500) NULL,
    [shopTelephone]               NVARCHAR (500) NULL,
    [shopLogo]                    NVARCHAR (500) NULL,
    [shopBusinessLicense]         NVARCHAR (500) NULL,
    [shopHygieneLicense]          NVARCHAR (500) NULL,
    [contactPerson]               NVARCHAR (500) NULL,
    [contactPhone]                NVARCHAR (500) NULL,
    [canTakeout]                  BIT            NULL,
    [canEatInShop]                BIT            NULL,
    [provinceID]                  INT            NULL,
    [cityID]                      INT            NULL,
    [countyID]                    INT            NULL,
    [shopStatus]                  INT            NULL,
    [isHandle]                    INT            NULL,
    [shopImagePath]               NVARCHAR (500) NULL,
    [shopDescription]             NVARCHAR (500) NULL,
    [prePayCashBackCount]         TINYINT        NULL,
    [prePayVIPCount]              TINYINT        NULL,
    [prePaySendGiftCount]         TINYINT        NULL,
    [sinaWeiboName]               NVARCHAR (100) NULL,
    [preorderCount]               BIGINT         NULL,
    [prepayOrderCount]            BIGINT         NULL,
    [preorderGiftTitle]           NVARCHAR (500) NULL,
    [preorderGiftDesc]            NVARCHAR (500) NULL,
    [preorderGiftValidTimeType]   TINYINT        NULL,
    [preorderGiftValidTime]       DATETIME       NULL,
    [preorderGiftValidDay]        INT            NULL,
    [preorderGiftValid]           INT            NULL,
    [qqWeiboName]                 NVARCHAR (100) NULL,
    [wechatPublicName]            NVARCHAR (100) NULL,
    [openTimes]                   VARCHAR (50)   NULL,
    [shopRegisterTime]            DATETIME       NULL,
    [shopVerifyTime]              DATETIME       NULL,
    [isSupportAccountsRound]      BIT            NULL,
    [remainMoney]                 FLOAT (53)     NULL,
    [totalMoney]                  FLOAT (53)     NULL,
    [shopRating]                  FLOAT (53)     NULL,
    [publicityPhotoPath]          NVARCHAR (500) NULL,
    [acpp]                        FLOAT (53)     NULL,
    [isSupportPayment]            BIT            NULL,
    [orderDishDesc]               NVARCHAR (500) NULL,
    [notPaymentReason]            NVARCHAR (300) NULL,
    [accountManager]              INT            NULL,
    [bankAccount]                 INT            NULL,
    [isSupportRedEnvelopePayment] BIT            CONSTRAINT [DF_ShopInfo_isSupportRedEnvelopePayment] DEFAULT ((1)) NULL,
    [ShopLevel]                   INT            NULL,
    [tmp]                         INT            NULL,
    CONSTRAINT [PK_ShopInfo] PRIMARY KEY CLUSTERED ([shopID] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'店铺级别', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ShopInfo', @level2type = N'COLUMN', @level2name = N'ShopLevel';

