CREATE TABLE [dbo].[EmployeeInfo] (
    [EmployeeID]              INT            IDENTITY (1, 1) NOT NULL,
    [UserName]                NVARCHAR (50)  NULL,
    [Password]                NVARCHAR (50)  NULL,
    [EmployeeFirstName]       NVARCHAR (50)  NULL,
    [EmployeeLastName]        NVARCHAR (50)  NULL,
    [EmployeeSex]             INT            NULL,
    [EmployeeAge]             INT            NULL,
    [EmployeePhone]           NVARCHAR (50)  NULL,
    [EmployeeSequence]        INT            NULL,
    [EmployeeStatus]          INT            NULL,
    [removeChangeMaxValue]    FLOAT (53)     NULL,
    [canQuickCheckout]        BIT            NULL,
    [canClearTable]           BIT            NULL,
    [canWeigh]                BIT            NULL,
    [position]                NVARCHAR (100) NULL,
    [defaultPage]             NVARCHAR (500) NULL,
    [loginCode]               VARCHAR (50)   NULL,
    [otherLoginCode]          VARCHAR (50)   NULL,
    [cookie]                  NVARCHAR (100) NULL,
    [verificationCode]        NVARCHAR (50)  NULL,
    [verificationCodeTime]    DATETIME       NULL,
    [employeeNumber]          NVARCHAR (50)  NULL,
    [cityId]                  INT            NULL,
    [isViewAllocWorker]       BIT            NULL,
    [isSupportShopManagePage] BIT            NULL,
    [settlementPoint]         FLOAT (53)     NULL,
    [notSettlementPoint]      FLOAT (53)     NULL,
    [registerTime]            DATETIME       NULL,
    [birthday]                DATETIME       NULL,
    [remark]                  NVARCHAR (MAX) NULL,
    [isSupportLoginBgSYS]     BIT            NULL,
    [isVCSendByVoice]         BIT            NULL,
    [pushToken]               NVARCHAR (100) NULL,
    [AppType]                 INT            NULL,
    CONSTRAINT [PK_EmployeeInfo] PRIMARY KEY CLUSTERED ([EmployeeID] ASC)
);

